#!/usr/bin/env bash

set -e

NODENV_COMMAND="$1"
NODENV_COMMAND_PATH="$(nodenv-which "$NODENV_COMMAND")"
NODENV_BIN_PATH="${NODENV_COMMAND_PATH%/*}"

shopt -s nullglob
for script in "$(dirname "${BASH_SOURCE[0]}")/../../etc/nodenv.d/exec/"*.bash; do
  source "${script}"
done
shopt -u nullglob

shift 1
echo NODENV_BIN_PATH="${NODENV_BIN_PATH}" exec -a "${NODENV_COMMAND}" "$NODENV_COMMAND_PATH" "$@"
exec -a "${NODENV_COMMAND}" "$NODENV_COMMAND_PATH" "$@"
